version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  nest-app:
    build: ./be
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  react-app:
    build: ./fe
    ports:
      - "3000:3000"